import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import AppBarWithMenu from '@/components/Appbar';
import React, { useState } from 'react';
import { ActiveLinkProvider } from './context/ActiveLinkContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ActiveLinkProvider>
          <AppBarWithMenu />
          <Navbar />
          {children}
        </ActiveLinkProvider>
      </body>
    </html>
  );
}
